### Variabel
@host = http://localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJuZXd1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xOVQwODo0OToxNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xOVQwOTo0ODo0OS4wMDBaIiwiaWF0IjoxNzQ3NjQ4MTQ5LCJleHAiOjE3NDc2NDkwNDl9.d6g3aF3-Md-MuX4seyzPIvPtggueEFvkl3DtA3R5BOM

### Registrasi pengguna baru
POST {{host}}/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

### Login dengan kredensial
POST {{host}}/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

### Dapatkan token akses baru dengan token refresh
GET {{host}}/token

### Logout
DELETE {{host}}/logout

### Ambil semua catatan
GET {{host}}/notes
Authorization: Bearer {{accessToken}}

### Tambah catatan baru
POST {{host}}/notes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Contoh Catatan",
  "content": "Ini adalah isi dari contoh catatan"
}

### Ambil catatan berdasarkan ID
GET {{host}}/notes/1
Authorization: Bearer {{accessToken}}

### Perbarui catatan
PUT {{host}}/notes/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Catatan Diperbarui",
  "content": "Ini adalah isi catatan yang sudah diperbarui"
}

### Hapus catatan
DELETE {{host}}/notes/1
Authorization: Bearer {{accessToken}}